#开发配置
# 使用druid数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/travplatform
    username: root
    password: k950101
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 200
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#以下配置使用 mybatis.xml  配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: ../registerpojo/com.business.register.pojo


